from gws_core import (
    ConfigParams,
    ConfigSpecs,
    CredentialsDataOther,
    CredentialsParam,
    CredentialsType,
    ListParam,
    OutputSpec,
    OutputSpecs,
    StrParam,
    Task,
    TaskInputs,
    TaskOutputs,
    Text,
    TextParam,
    TypingStyle,
    task_decorator,
)

from gws_ai_toolkit.rag.ragflow.ragflow_class import (
    RagFlowCreateChatRequest,
    RagFlowUpdateChatRequest,
)
from gws_ai_toolkit.rag.ragflow.ragflow_service import RagFlowService


@task_decorator(
    "RagFlowCreateOrUpdateChat",
    human_name="Create or Update RagFlow Chat",
    short_description="Create a new or update an existing RagFlow chat assistant",
    style=TypingStyle.community_image("ragflow", "#4A90E2"),
)
class RagFlowCreateOrUpdateChat(Task):
    """
    [Generated by Task Expert Agent]

    Create a new chat assistant or update an existing one in RagFlow.

    If a **Chat ID** is provided, the existing chat is updated with the given parameters.
    Otherwise, a new chat assistant is created.

    ## Usage
    - **Output**: A Text resource containing the chat assistant ID

    ## Configuration
    - `api_key`: RagFlow credentials (route + api_key)
    - `name`: Name for the chat assistant
    - `prompt`: System prompt / instructions for the chat assistant
    - `dataset_ids`: List of dataset IDs to link as knowledge bases
    - `model_name`: LLM model name (default: "gpt-5")
    - `chat_id`: (Optional) Existing chat ID to update instead of creating a new one
    """

    output_specs = OutputSpecs({
        "chat_id": OutputSpec(
            Text,
            human_name="Chat ID",
            short_description="The ID of the created or updated RagFlow chat assistant",
        ),
    })

    config_specs = ConfigSpecs({
        "api_key": CredentialsParam(
            credentials_type=CredentialsType.OTHER,
            human_name="RagFlow API Key",
            short_description="A credentials that contains 'route' and 'api_key'",
        ),
        "name": StrParam(
            human_name="Chat name",
            short_description="Name for the chat assistant",
        ),
        "prompt": TextParam(
            human_name="Chat prompt",
            short_description="System prompt / instructions for the chat assistant",
        ),
        "dataset_ids": ListParam(
            default_value=None,
            optional=True,
            human_name="Dataset IDs",
            short_description="List of dataset IDs to link as knowledge bases",
        ),
        "model_name": StrParam(
            default_value="gpt-5",
            human_name="Model name",
            short_description="LLM model name for the chat assistant",
        ),
        "chat_id": StrParam(
            default_value=None,
            optional=True,
            human_name="Chat ID",
            short_description="Optional existing chat ID — if provided, the chat is updated instead of created",
        ),
    })

    def run(self, params: ConfigParams, inputs: TaskInputs) -> TaskOutputs:
        credentials: CredentialsDataOther = params.get_value("api_key")
        ragflow_service = RagFlowService.from_credentials(credentials)

        name: str = params.get_value("name")
        prompt: str = params.get_value("prompt")
        knowledgebases: list[str] = params.get_value("dataset_ids") or []
        model_name: str = params.get_value("model_name")
        chat_id: str | None = params.get_value("chat_id")

        prompt_config = {"prompt": prompt}
        llm_config = {"model_name": model_name}

        if chat_id:
            # Update existing chat
            self.log_info_message(f"Updating existing chat '{chat_id}'...")

            update_request = RagFlowUpdateChatRequest(
                name=name,
                knowledgebases=knowledgebases if knowledgebases else None,
                llm=llm_config,
                prompt=prompt_config,
            )
            chat = ragflow_service.update_chat(chat_id, update_request)
            chat_id = chat.id

            self.log_success_message(f"Chat updated: {chat_id}")
        else:
            # Create new chat
            self.log_info_message(f"Creating new chat assistant '{name}'...")

            create_request = RagFlowCreateChatRequest(
                name=name,
                knowledgebases=knowledgebases,
                llm=llm_config,
                prompt=prompt_config,
            )
            chat = ragflow_service.create_chat(create_request)
            chat_id = chat.id

            self.log_success_message(f"Chat created with ID: {chat_id}")

        return {"chat_id": Text(chat_id)}
